### ISSUE TITLE
local server exit with code 1(have you launch another server?)

### ISSUE THREAD

**Issue by edwinkepler** [hangxingliu/vscode-coding-tracker#12]
In stdout:

[Error]: /home/user/.vscode/extensions/hangxingliu.vscode-coding-tracker-0.4.1/node_modules/vscode-coding-tracker-server/lib/Storage.js:1 (function (exports, require, module, __filename, __dirname) { let Path = require('path'), 

Arrows shows `{ let Path` part.

EDIT: I'm not running any other servers.

CodingTracker ver 0.4.1
VSCode ver 1.15.1

**Comment by edwinkepler** [comment]
I'm sorry, I had ancient node. **Updating node** to the newest version fixed that problem.

**Comment by hangxingliu** [comment]
Yes, Because `let` is not support before `Node.js 5` without  `strict mode`
