### ISSUE TITLE
Hide the icon from status bar

### ISSUE THREAD

**Issue by athahersirnaik** [hangxingliu/vscode-coding-tracker#13]
Can you please hide the Coding Tracker from status bar, it occupies a whole lot of space. Let me know if you want help with the same.

**Comment by hangxingliu** [comment]
Good idea. I will add this function into extension around 5th September after I  finish my holiday. Or you can give this repository PR

**Comment by hangxingliu** [comment]
Added: <https://github.com/hangxingliu/vscode-coding-tracker/commit/81d471dab1217c2248e078863ccade2b53c2b2f6>

**Comment by athahersirnaik** [comment]
Thanks
