### ISSUE TITLE
Monthly Report

### ISSUE THREAD

**Issue by braga-bruno** [hangxingliu/vscode-coding-tracker#15]
This is a great plugin for VS Code! Are you planning to add monthly or custom range summary? I really need a monthly code time report

**Comment by hangxingliu** [comment]
I will add it into next version <https://github.com/hangxingliu/vscode-coding-tracker-server>

**Comment by hangxingliu** [comment]
I have added into server side code, commit: <https://github.com/hangxingliu/vscode-coding-tracker-server/commit/c3380db364ea6c021f64298f254fb4b072a6404b>

It will be released in next version.
