### ISSUE TITLE
Exporting tracked data or moving the server 

### ISSUE THREAD

**Issue by tinytom** [hangxingliu/vscode-coding-tracker#17]
Hi,
I am reinstalling my OS and I would like to keep my coding activity. 
Is there possibility to export the tracked data from this extension? Maybe it would be enough to copy the extension folder and then paste it into later installation of vscode ? 
Thanks

**Comment by hangxingliu** [comment]
yes, you can just copy folder `.coding-tracker` folder in your home folder.

for windows user: `C:\Users\XXX\.coding-tracker`
for linux user: `/home/XXX/.coding-tracker`

**Comment by hangxingliu** [comment]
@tinytom Have you resolved ?

**Comment by tinytom** [comment]
@hangxingliu I am sorry I didn't answer sooner as I continued my backup process of VS extensions and I noticed `.coding-tracker` folder and from then it was easy process. So yes, everything alright.

_Notice for debian users to not forget installing npm and nodejs, this extension was not working without it._
