### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by robjloranger** [hangxingliu/vscode-coding-tracker#27]
Thank you for this plugin and server combo. It is awesome. I was using the free version of wakatime but now will no longer need to. As well this would let me see my activity from farther back than the last week.

Thanks again :grinning:

**Comment by hangxingliu** [comment]
You are welcome, I am also happy for this project can help others. This project has many places could be improved. So I am developing continuously although the update is slow because I have many assignments and works too. And I also welcome pull request from everyone to make it better.
