### ISSUE TITLE
How is it possible?

### ISSUE THREAD

**Issue by ted-piotrowski** [hangxingliu/vscode-coding-tracker#3]
![screen shot 2017-02-07 at 5 37 44 pm](https://cloud.githubusercontent.com/assets/2023571/22678070/3df43b74-ed5c-11e6-8f29-35e9ef2a7dce.png)

I spent more than 1 hour coding/looking between 10-11am. I am working super hard. 🤣

**Comment by hangxingliu** [comment]
Haha, I think that we got different meanings about these two type of time.
Actually, Coding time is a subset of Watching time.(Watching time included Coding time)
So. You would get less than one hour Watching time in each hour.
(P.s. I think that you are watching the screen when you are coding. So I developed Coding time as a part of Watching time)
