### ISSUE TITLE
hi, I think it will more interesting.

### ISSUE THREAD

**Issue by ppxialetsgo** [hangxingliu/vscode-coding-tracker#5]
Do you consider to add 'share to somewhere' ？

**Comment by hangxingliu** [comment]
I think it is a good idea.
I will add a share button to the report page. (and more future)
(P.s. I saw you have fork this project. you can give me pull request if you want to contribute your good idea by yourself)

**Comment by cooooding** [comment]
its ok.



在 LiuYue <notifications@github.com>，2017年3月7日 16:33写道：

I think it is a good idea.
I will add a share button to the report page. (and more future)
(P.s. I saw you have fork this project. you can give me pull request if you want to contribute your good idea by yourself)

**Comment by hangxingliu** [comment]
"Share" has been added into coding-tracker
<https://github.com/hangxingliu/vscode-coding-tracker-server/commit/951db54d045c13a9bc3f6cfdb9e2b5496310b2b3>

You can enjoy this function after next time your VSCode tell you upgrade `vscode-coding-tracker` extension.
Or you go to your extension folder. and edit your package.json file: replace dependency version  from "^0.3.1" to "^0.4.0". and executing `npm i` in same folder.

===========================

下次更新插件就会有分享按钮了. 或者你自己去插件目录下手动更新一下以来版本, 方法:
编辑插件目录下的package.json, 把最后"dependencies"中的"^0.3.1" 改成 "^0.4.0", 然后执行`npm i`, 重启一次VSCode就行了
